[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.22"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]


[tool.cibuildwheel]
build-verbosity = 3
before-all = [
    "yum install -y openssl-devel bzip2-devel libffi-devel zlib-devel wget python3-devel",
]

environment = "CMAKE_ARGS_F=/tmp/cmake_args"
before-build = [
    "rm -rf {project}/CMakeCache.txt {project}/build {project}/CMakeFiles.txt {project}/_deps",
    "pip install pyarrow==9.0.0",
    "export PYST=$(python -c 'import site; print(site.getsitepackages()[0])')",
    "ln -s $PYST/pyarrow/libarrow_python.so.900 $PYST/pyarrow/libarrow_python.so",
    "echo \"-DCMAKE_BUILD_TYPE=Release -DPYARROW_DIR=${PYST}/pyarrow/\" > ${CMAKE_ARGS_F}",
    "mkdir -p build/ukv"
]

skip = ["*musllinux*", "*i686*", "pp*", "cp36-*", "cp311-*"]

# Add Tests later
# test-command = "pytest {project}/python/tests/" 
# test-requires = ["pandas"]
# test-extras = ["test"]

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"