name: Build

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: apt dependencies
        run: |
          arrow_version=9.0.0-1 && sudo apt update && sudo apt install -y -V ca-certificates lsb-release wget && cd /tmp \
          && wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb \
          && sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb \
          && sudo apt update && sudo apt install -y -V libarrow-dev=${arrow_version} libarrow-dataset-dev=${arrow_version} libarrow-flight-dev=${arrow_version} \
          libarrow-python-dev=${arrow_version} libarrow-python-flight-dev=${arrow_version} libgandiva-dev=${arrow_version} libparquet-dev=${arrow_version} \
          python3.9 python3-pip python3-dbg python3.9-dev

      - name: pip dependencies
        run: python3.9 -m pip install --force-reinstall pytest numpy pyarrow cmake

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        run: make -j4 ukv_umem ukv_umem_unit_test ukv_umem_twitter_benchmark ukv_umem_tabular_graph_benchmark ukv_umem_api_test ukv_umem_compilation_test ukv_umem_stress_test

      - name: Upload Binaries
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ubuntu_binaries
          path: build/bin/*

  test:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ubuntu_binaries

      - name: Change Permissions
        run: chmod +x /home/runner/work/UKV/UKV/*
      - name: Run tests
        run: find /home/runner/work/UKV/UKV/ -iname '*unit_test' -exec {} \;
