name: Tests

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ubuntu_binaries
          path: build/bin/*

      - name: Run tests
        run: find ./build/bin/ -iname '*unit_test' -exec {} \;
